language: android
dist: xenial
os: linux

android:
 components:
    - tools
    - platform-tools
    - tools
    # Note that the tools section appears twice on purpose as it’s required
    # to get the newest Android SDK tools. Source: Travis CI docs.
    - build-tools-30.0.3
    - extra
    
notifications:
  email: true
    
before_install:
- yes | sdkmanager "platforms;android-30"

before_script:
- chmod +x gradlew

script:
- ./gradlew assembleDebug

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "someName"
  - git config --local user.email "someName@users.noreply.github.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - echo $GITHUB_TOKEN

deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
  name: dev-build-$TRAVIS_TAG
  release_notes: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  draft: true
  target_commitish: $TRAVIS_COMMIT

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
